CREATE TABLE dados_regiao (
    ano INT,
    nome_grande_regiao VARCHAR(100),
    sigla_unidade_federacao CHAR(2),
    nome_unidade_federacao VARCHAR(100),
    nome_municipio VARCHAR(150),
    regiao_metropolitana VARCHAR(100),
    nome_microrregiao VARCHAR(150),
    tipo_concentracao_urbana VARCHAR(100),
    amazonia_legal BOOLEAN,
    semiarido BOOLEAN,
    cidade_regiao_sao_paulo BOOLEAN,
    valor_adicionado_agropecuaria NUMERIC(15,2),
    valor_adicionado_industria NUMERIC(15,2),
    valor_adicionado_servicos NUMERIC(15,2),
    valor_adicionado_adm_saude_educ NUMERIC(15,2),
    valor_adicionado_total NUMERIC(15,2),
    impostos_liquidos_subsidios NUMERIC(15,2),
    pib NUMERIC(15,2),
    pib_per_capita NUMERIC(15,2),
    atividade_maior_valor_adicionado VARCHAR(150),
    atividade_segundo_maior_valor_adicionado VARCHAR(150),
    atividade_terceiro_maior_valor_adicionado VARCHAR(150)
);
